-- Table for registered admin users
CREATE TABLE IF NOT EXISTS admin_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email_hash CHAR(64) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user (email_hash)
);

-- table for account codes
CREATE TABLE IF NOT EXISTS account_codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_code VARCHAR(255) NOT NULL,
    account_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- default sql insert for acountcode autogenerated accountcode starting with NYADM-random numbers
INSERT INTO account_codes (account_code, account_name) VALUES ('NYADM-45624', 'Admins');